name: build xcaddy

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Go environment
        uses: actions/setup-go@v3.1.0
        with:
         go-version: 1.18
         
      - name: xcaddy
        run: |
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
          export version=$(curl -s "https://api.github.com/repos/caddyserver/caddy/releases/latest" | jq -r .tag_name)
          xcaddy build ${version} --output ./caddy_${version} \
          --with github.com/abiosoft/caddy-exec \
          --with github.com/caddy-dns/cloudflare \
          --with github.com/caddy-dns/dnspod \
          --with github.com/greenpau/caddy-auth-portal \
          --with github.com/greenpau/caddy-trace \
          --with github.com/hairyhenderson/caddy-teapot-module \
          --with github.com/kirsch33/realip \
          --with github.com/porech/caddy-maxmind-geolocation \
          --with github.com/caddyserver/transform-encoder \
          --with github.com/mholt/caddy-webdav \
          --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive
        
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/cfg/gpg/gpg.155B6D79CA56EA34.key' | sudo apt-key add -
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/cfg/setup/config.deb.txt?distro=debian&version=any-version' | sudo tee -a /etc/apt/sources.list.d/caddy-stable.list
          sudo apt update
          sudo apt install caddy
          sudo killall caddy
          sudo rm -f /usr/bin/caddy
          sudo mv ./caddy_${version} /usr/bin/caddy
          
          
      - uses: actions/upload-artifact@v3
        with:
          name: caddy
          path: /usr/bin/caddy
          
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: caddy
          file: /usr/bin/caddy
          tag: ${{ github.ref }}
          overwrite: true
      
